const constants = {
    FETCH_ISSUES: "FETCH_ISSUES",
    FETCH_ISSUE_COUNT: "FETCH_ISSUE_COUNT",
    FETCHING_STATE: "FETCHING_STATE",
    CANCEL_FETCHING: "CANCEL_FETCHING",
    GET_ISSUES: "GET_ISSUES",
    GET_PAGINATED_ISSUES: "GET_PAGINATED_ISSUES",
    FILTER_ISSUE_STATE: "FILTER_ISSUE_STATE",
    SORT_ISSUE: "SORT_ISSUE",
    FETCH_ISSUE_DESCRIPTION: "FETCH_ISSUE_DESCRIPTION",
    ADD_COMENTS: "ADD_COMENTS",
	ADD_ERROR: "ADD_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR",
    SET_USER_DATA: "SET_USER_DATA",
    SET_HEADERS: "SET_HEADERS",
    SET_ISSUE_COMMENT: "SET_ISSUE_COMMENT",
    ISSUES_COMMENTS: "ISSUES_COMMENTS",
    ISSUE_DATA: "ISSUE_DATA"
}

export default constants